_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.11
            "5": 0.18.2
            "8":
                - 6
            "12": 0.18.2
            "13": linux-x86_64
atom_hidden_size:
    value: 32
atom_noise:
    value: 0
atom_weight:
    value: 1
balanced_sampler:
    value: false
batch_size:
    value: 1
block_embedding_size:
    value: null
block_embedding0_size:
    value: null
block_embedding1_size:
    value: null
block_hidden_size:
    value: 23
bottom_global_message_passing:
    value: true
cycle_steps:
    value: 100000
dropout:
    value: 0
edge_size:
    value: 32
final_lr:
    value: 5e-06
fragmentation_method:
    value: null
global_message_passing:
    value: true
gpus:
    value:
        - 0
grad_clip:
    value: 1
k_neighbors:
    value: 8
local_rank:
    value: -1
lr:
    value: 0.0001
mask_proportion:
    value: 0
mask_weight:
    value: 1
max_epoch:
    value: 200
max_n_vertex_per_gpu:
    value: 512
max_n_vertex_per_item:
    value: 512
max_rotation:
    value: 0.7853981633974483
modality_embedding:
    value: false
n_layers:
    value: 4
noisy_nodes_weight:
    value: 0
num_classifier_classes:
    value: null
num_nodes:
    value: null
num_pred_layers:
    value: 4
num_projector_layers:
    value: 3
num_workers:
    value: 1
partial_finetune:
    value: false
patience:
    value: 30
pred_dropout:
    value: 0
pred_hidden_size:
    value: 64
pred_nonlinearity:
    value: relu
pretrain_ckpt:
    value: null
pretrain_config:
    value: ./project-training/original-model-config/pretrain_model_config.json
pretrain_state:
    value: null
pretrain_weights:
    value: ./project-training/original-model-config/pretrain_model_weights.pt
projector_dropout:
    value: 0
projector_hidden_size:
    value: 256
rot_weight:
    value: 1
rotation_noise:
    value: 0
run_name:
    value: new-run-saturday
save_dir:
    value: ./project-training/model-outputs
save_topk:
    value: -1
seed:
    value: 12
shuffle:
    value: true
task:
    value: PDBBind
tor_weight:
    value: 1
torsion_noise:
    value: 0
tr_weight:
    value: 1
train_set:
    value: ./project-training/data/train_items.pkl
train_set2:
    value: null
train_set3:
    value: null
translation_noise:
    value: 0
use_raytune:
    value: false
use_wandb:
    value: true
valid_batch_size:
    value: 1
valid_max_n_vertex_per_gpu:
    value: 512
valid_set:
    value: ./project-training/data/val_items.pkl
valid_set2:
    value: null
valid_set3:
    value: null
warmup_end_lr:
    value: 0.001
warmup_epochs:
    value: 0
warmup_start_lr:
    value: 1e-05
